### ISSUE TITLE
Create Cassandra CDC Source

### ISSUE THREAD

**Issue by andrewstevenson** [Landoop/stream-reactor#162]
http://cassandra.apache.org/doc/latest/operating/cdc.html

**Comment by criccomini** [comment]
I have a question on the design of this source. It really has more to do with the Cassandra CDC implementation, but I think it's relevant here.

How will this source implementation handle the case where a given Cassandra node fails? As I read the CDC document, the SST files are written to a directory on a given node. Are these SST files the same across all nodes? If not, it seems like it'd be impossible to fail over from one node to the other without some special logic to figure out in which SST the source should pick up from. If the two SST directories ARE identical, then we can probably just run Kafka connect in distributed mode on N of the Cassandra nodes--a failure would cause Kafka connect to rebalance, and the connector would pick up where it left off.

**Comment by stheppi** [comment]
@criccomini 
Chris we are yet to start the implementation. we are going to find out the answer to your question soon.

**Comment by criccomini** [comment]
Checking in on this.

**Comment by AkshathPatkar** [comment]
checking on this.

**Comment by andrewstevenson** [comment]
@AkshathPatkar We have started figuring out the internal mutations written to the logs so it's in progress.

**Comment by AkshathPatkar** [comment]
@andrewstevenson 👍

**Comment by andrewstevenson** [comment]
@criccomini 

Early feed appreciated http://docs.datamountaineer.com/en/latest/cassandra-cdc.html

**Comment by criccomini** [comment]
Woot! Reading now

**Comment by criccomini** [comment]
@andrewstevenson 

# Cassandra CDC

> messages sent to Kafka are in AVRO format.

Shouldn't the connector just be using SourceRecord, and allow Kafka Connect config to define the serialization format? We use Avro+Confluent Schema Reg.

> Once the disk space limit is reached, writes to CDC enabled tables will be rejected until space is freed.

What mechanism is cleaning old legs from the CDC folder? Does Cassandra do this? Or the Connector? Or a CRON job? The docs read like the connector handles deletion after it processes the CDC file. Just want to confirm.

> and will push them to the target topic

How does the mapping work between Cassandra tables and Kafka topics?  The docs read like there is just a single topic. We would much rather the mapping be one table->one topic. For one thing, this gives us the ability to enable compatibility checks in Confluent schema registry. It’s also much cleaner, since consumers can pick just the tables (topics) that they care about.

> "changeType": //The type of change in Cassandra

The Key should not contain the change type. You shouldn’t have any dynamic data in the key (i.e. fields that change between insert/update/delete). The reason for this is that it is a common pattern to use Kafka log compacted topics with CDC feeds. In order for log compaction to work properly, the keys for a given row must be identical across mutations.

> "timestamp" : //the timestamp of when the change was made in Cassandra

Same as above.

> "deleted_columns": //which columns have been deleted. We will expand on the details

Same as above.

> It is expected that Kafka Connect worker will run on the same node as the Apache Cassandra node.

In distributed mode or standalone?

> Upon flushing the memtable to disk, all the commit log segments containing data for CDC-enabled tables are moved to the configured cdc_raw directory

What is the normal frequency with which this occurs? I’m trying to get a feel for how much latency there will be.

> The connector is driven by the configurations and not by the list of all the tables with CDC enabled. (Might be a feature, change to do)

+1 Would very much like to have this as a feature.

>     "connect.cassandra.kcql":"INSERT INTO orders-topic SELECT * FROM datamountaineer.orders",

How would we configure the connector if we wanted to consume more than one topic? For example, if we had two tables: orders, and payments, and we wanted the orders table to go to the orders topic, and the payments table to go to the tables topic? Would this require two instances of the connector, each with different config, or is there a way to configure this for a single Cassandra CDC connector?

> The maximum number of Cassandra mutation to buffer. As it reads from the Cassandra CDC files the mutations are buffered before they are handed over to Kafka Connect.	

You always flush the buffer before the CDC file is deleted, right?

> The worker CDC thread will read a CDC file checking if any of the processed files are ready to be deleted (that means the records have been sent to kafka). Rather than waiting for a read to complete we can delete the files while reading a CDC file. a CDC file. You can disable it for faster faster reads by setting the value to false.	

wat? :)

> connect.cassandra.cdc.single.instance.port ra.cdc.single.i

This looks like nonsense. Probably a typo?

Other questions:

* How does a node failure get handled?
* Is there just one connect CDC process running on a single node? Cassandra is sharded, so I’m assuming you have to have the connector running on every node. How does this work in Kafka connect distributed mode? I guess I’m just a bit confused about the topology and deployment relationship between Kafka connect, the connector, and the Cassandra nodes. Based on some hints in the configuration table, it sounds like  you force one task per worker by grabbing a port. What happens when a worker is down for a period of time? Does that extra worker just bounce from worker to worker causing rebalances in Kafka connect?
* Want to confirm that there’s no possibility for data loss (even when failure occurs).

**Comment by criccomini** [comment]
> Kafka Connect framework doesn’t allow yet configuration where you are running only one task per worker

Is there a KAFKA JIRA for this?

**Comment by criccomini** [comment]
Another question: does the Cassandra CDC connector support snapshotting of existing tables? For example, if I have a table that's existed for a year, and I alter it to enable CDC, then configure the connector to consume it, how do I get the old data?

**Comment by stheppi** [comment]
@criccomini 

i will try to clarify some of your statements.

1. *messages sent to Kafka are in AVRO format*.  
To clarify how connect works.  The connector does create a SourceRecord and sets the value/key schema to a Connect schema. Since the converter is set to AvroConverter  it will end up calling AvroData (see confluent schema-registry repo for its implementation) which converts the Connect Schema to an Avro Schema and Connect Struct to an Avro GenericRecord.  The AvroConverter will work with SchemaRegistry to establish the schema id which is added at the beginning of the binary array which results as part of the serialization. This is how the translation happens. So the connector does all the right thing hence the payload on the topic is AVRO. 

2. *What mechanism is cleaning old logs from the CDC folder? Does Cassandra do this? Or the Connector? Or a CRON job? The docs read like the connector handles deletion after it processes the CDC file. Just want to confirm.*
I think you missed the documentation **How does it work** section. "The Connect source will process the files in the order they were created and one by one. This ensures the change sequence is retained. Once the records have been pushed to Kafka **the CDC file is deleted.**"

3*The Key should not contain the change type. You shouldn’t have any dynamic data in the key (i.e. fields that change between insert/update/delete). The reason for this is that it is a common pattern to use Kafka log compacted topics with CDC feeds. In order for log compaction to work properly, the keys for a given row must be identical across mutations.*
Valid point we will look to change.

4. *What is the normal frequency with which this occurs? I’m trying to get a feel for how much latency there will be.* the documentation says it can't be predicted. when the memtable is filled that's when it is flushed. depending on Cassandra settings and volumes it could be days. A user might need to schedule these fluses.

5 *+1 Would very much like to have this as a feature.* it already does - it's implemented.

6. *How would we configure the connector if we wanted to consume more than one topic? For example, if we had two tables: orders, and payments, and we wanted the orders table to go to the orders topic, and the payments table to go to the tables topic? Would this require two instances of the connector, each with different config, or is there a way to configure this for a single Cassandra CDC connector?*  I think the documentation specifies ``connect.cassandra.kcq`` : ``..  It describes which CDC tables are monitored and the target Kafka topic for Cassandra CDC information.`` we will make it clearer one can say `` INSERT INTO payments SELECT * FROM datamountaineer.payments; INSERT INTO orders SELECT * FROM datamountaineer.orders``

7. *You always flush the buffer before the CDC file is deleted, right?* yes otherwise we can lose data

8.  "wat? :)"  -> a file is read one by one and the buffer is filled. there is a dedicated thread that does that. Meanwhile Connect thread will asks for records from this buffer. It could happen as the a CDC file is read the records for the previous file to be consumed and thus the prev CDC file is eligible to be deleted. this option allows to check while a file is read if the previous file/-s can be deleted. this check for files to be deleted happens anyway but not while a CDC file is read.

9. *This looks like nonsense. Probably a typo?* yes. should be ``connect.cassandra.cdc.single.instance.port ``


10. *How does a node failure get handled?* if its connect failure we retain the file and mutation location thus on restart it is picked up from where it left. if Cassandra node goes down that connect node will consume whatever is left there and then there won't be much to do since no more CDC files will be spit out on that machine. If the machine fails totally the CDC logs contain the data even on replica nodes ( Cassandra CDC documentation)

11. *Is there just one connect CDC process running on a single node? Cassandra is sharded, so I’m assuming you have to have the connector running on every node. How does this work in Kafka connect distributed mode?...*   yes the documentation should be clear enough stating there has to be a 1-1 relationship between Cassandra process and Connect worker process. The reason for the port grabbing is to allow one instance of task per worker really active. We can't have two threads reading the CDC files. If a machine goes down Connect will rebalance and 2 tasks will be allocated on one worker. Then only 1 can be active!

12. *Want to confirm that there’s no possibility for data loss (even when failure occurs).* That's what we worked out based on the implementation we have so far. however more testing is required. remember the version we have is BETA!!

13. *How does the connector handle the fact that some Cassandra nodes have data that's a replica from another node (or nodes)? Does it send a ton of duplicate rows, or does it de-duplicate such that each row is only sent once?*  Connect doesn't deduplicate it can't by its nature. you don't want two Connect tasks on different machines to start synchronising.  Unfortunately Cassandra having a masterless architecture and the implementation choosing this file based logging (rather than say a TCP listener) the dedup needs to happen at consumption. But processing the records sent on the topic eventual consistency is achieved.

Please remember the implementation so far is only BETA. We would like early adopters in DEV to give it a try and help with testing and any potential problems

**Comment by stheppi** [comment]
If the memtable has been flushed to the disk and CDC wasn't enable you won't get those commits. That's what i understand. but that's a question for the Apache Cassandra community more than us.

**Comment by criccomini** [comment]
> If the memtable has been flushed to the disk and CDC wasn't enable you won't get those commits. That's what i understand. but that's a question for the Apache Cassandra community more than us.

This is a pretty big deal. Basically, it precludes anyone from using this connector if they are already running Cassandra. In addition, it means you'll have to t

To be frank, supporting a `snapshot` feature when tables are first added is a pretty big priority. This is something that Debezium added early on, and without it, it's going to severely limit the usefulness of the connector.

> the dedup needs to happen at consumption

This is what I was afraid of. Do you have a hint on how to do this? Do we use the timestamp, and highest timestamp wins?

**Comment by criccomini** [comment]
As far as snapshots go, perhaps this can be leveraged?

http://docs.datastax.com/en/cassandra/3.0/cassandra/operations/opsAboutSnapshots.html

**Comment by stheppi** [comment]
We can add a read all table upfront and then start the connector. but to enable the cdc you need to restart your cassandra cluster. you can do it node by node to avoid downtime but that means the snapshot is not accurate. We might build that tool as well but it still down to the user to decide if this is required. This shouldn't be enforced. 
I fully understand the concerns but this is still work in progress and we appreciate early feedback hence we made it public.
But there are a few things to bare in mind :
1. it's open source hence people can contribute.
2. it might require some work from the Apache Cassandra community (if there are limitations and not just gaps in our understanding)
3. development is still in progress 

dedup: you have the key for the cassandra record and the mutation timestamp. you can use the timestamp. But if you process let them to be processed you will still end up with the right value after all records have been processed. this avoid the check for 'have-i-processed-this-entry'

**Comment by criccomini** [comment]
> We can add a read all table upfront and then start the connector.

+1 This is what I was getting at. This is how Debezium does it. One thing to consider is how the read all works vs how the CDC works. In Debezium land (on MySQL), there's a SELECT * that runs (similar to MySQL dump), then it flips to the MySQL binlog at exactly the point that the SELECT * ran. Given that Cassandra is distributed and there's no de-dupe, I anticipate that the dump/CDC flip will be more complicated, but it's worth thinking through a bit.

> but to enable the cdc you need to restart your cassandra cluster.

Understood. I don't think that this is something you guys should solve for. Make your lives easier, and ops folks can determine the best way to make this change.

Totally get that this is open source, and beta. Don't get me wrong, I'm stoked that you guys are doing this. My main motivation is in making sure you guys are aware of all these edge cases, and what's going to be required to really use this thing in production. We've already gone through this dance with the Debezium community on the MySQL side of things, so I'm trying to apply learnings from that to this problem.

**Comment by stheppi** [comment]
we appreciate the feedback so far

**Comment by criccomini** [comment]
NP.

It's also still unclear to me how your current solution is going to be have when a node is down for an extended period of time. IIRC, you are using a port-binding trick to force one task per node. But if you have 10 nodes and 10 tasks, and then a node dies, the task on that node will be rebalanced to a new node, right? This will go on until the dead node comes back. This could go on for quite some time, and the rebalancing will just keep happening because there are now 9 nodes and 10 tasks. This can be really disruptive since a rebalance in Kafka connect currently (at least as of 0.10) rebalances ALL tasks every time there's a rebalance.

This is vs. running the connector in standalone mode, one per node. When a node goes down, both the Cassandra node and the connector on that box are then down. No rebalance occurs. When the node comes back, both Cassandra and the standalone connector are started up again.

**Comment by stheppi** [comment]
' the task on that node will be rebalanced to a new node, right? This will go on until the dead node comes back' -> that is not true. the rebalance will complete without requiring the node which died to be back up. 
We chose the distributed version to be able to monitor it as one connector. think of a 100nodes cluster. you will have 100 connectors.

on the dedup: if the target can store and reading the ts we are good thus having the streaming dedup is quite an overhead. plus as i said earlier some might choose to consume the change data since eventually is consistent.

**Comment by criccomini** [comment]
> that is not true. the rebalance will complete without requiring the node which died to be back up.

Can you describe how that will happen? I think I'm lacking some understanding in this area. What I described above w.r.t. the 10 task/9 node problem seems to apply.

**Comment by criccomini** [comment]
Also, regarding my "how frequently do the CDC files get shifted", there's an interesting patch floating in the Cassandra JIRA slated for a 4.x release:

https://issues.apache.org/jira/browse/CASSANDRA-12148

**Comment by stheppi** [comment]
Connect is using the Kafka consumer group semantics for the workers. Hence if a worker has died the remaining 9 will rebalance and distribute the tasks amongst themselves. if 9 workers are running you will see one of the workers spinning up 2 tasks.  

http://docs.confluent.io/current/connect/concepts.html should give you more details

**Comment by criccomini** [comment]
> if 9 workers are running you will see one of the workers spinning up 2 tasks.

Yes, but if one worker has two tasks, the first task will "grab the port". The second task on the node will fail to "grab the port" because it's already bound to the first task, right? I'm assuming this causes the second task to fail, which would trigger a rebalance, wouldn't it?

**Comment by stheppi** [comment]
Let me clarify that part. If it fails we capture the exception and we don't initialise the cdc logic. that task sits there basically doing nothing. Thus no new rebalance is triggered

**Comment by criccomini** [comment]
Ah ha. That's the piece I was missing. In that case, though, I don't think Kafka connect is smart about balancing tasks across its nodes. If we have 10 nodes and 10 tasks, what stops KC from assigning 3 tasks to node 0 and no tasks to nodes 1 or 2. We see this happen all the time with our production Kafka connect cluster--things can be imbalanced. If the tasks that fail to bind don't get rebalanced, then some Cassandra nodes won't have any tasks at all on them, right?

**Comment by andrewstevenson** [comment]
Connect round robins the tasks onto workers,  i know there was some talk of changing this. So if we have 10 workers with one on each Cassandra node and 10 tasks we should be ok. We should be able to test this once we get our integration tests going.

**Comment by criccomini** [comment]
Sounds good.

**Comment by criccomini** [comment]
Another thought: Debezium's value payload has both a "before" and "after" to show the diff of what changed. Not sure if the CDC files expose that (I kind of doubt it), but if so, it'd be useful to expose both the before and after fields.

**Comment by stheppi** [comment]
I am affraid debezium leverage the product and its capabilities. Unfortunately Cassandra CDC doesn't provide that. But someone consuming ( there will be a consumer) can work out  the prev value.

**Comment by criccomini** [comment]
Ya, that's what I figured. Just wanted to confirm. Consumers can always maintain state if they want to know the previous value.

**Comment by Antwnis** [comment]
Adding for reference @criccomini blog
https://medium.com/@criccomini/so-you-want-to-build-a-kafka-connector-source-edition-357dce7d55f4

**Comment by andrewstevenson** [comment]
@criccomini We'll get in the 0.3.1 release, we are busy with http:://kafka-lenses.io and 0.3.0  at the moment.

**Comment by joesankey** [comment]
Is this effort still active?

**Comment by Antwnis** [comment]
There are some limitations with the way Cassandra 3.x creates CDC records. We will probably pick work up again once Cassandra 4.x is out (TBD) @joesankey

**Comment by criccomini** [comment]
@Antwnis can you be specific about the limitations? Curious about this. cc @joesankey

**Comment by criccomini** [comment]
(Note: Cassandra 4.0 JIRA tracker is [here|https://issues.apache.org/jira/projects/CASSANDRA/versions/12336842])

**Comment by stheppi** [comment]
@criccomini 
  It is a bit surprising  to have you ask for the limitations since we discussed some of them with you already.  You have been very kind to provide feedback and we really appreciate it!  Rare thingy to be honest this days. Most people simply say i am all up for open source but they don't give back anything. Funny to be honest.

I will start with one. Imagine you have been in production with Cassandra for a number of years. Meanwhile have accumulated quite a lot of records to your table and now you switch on CDC.  And you have to ship all those records to Kafka meanwhile your instance is up and running and updates can occur. So you have to sync those two but you don't have a bridge between them.

Next is the dedup of records issue. As a node goes down and another one picks up we might send some records again. Next issue is timing. Until Cassandra doesn't flush the tables there are no updates. Depending on configs that could be even days.

We are welcoming any PRs or suggestions.

**Comment by criccomini** [comment]
@stheppi Does 4.0 solve these issues? :) Or are you just using it as a milestone to start working on this again?

Another issue I was alerted of recently is that Cassandra CDC files don't have full row data in them, just the fields that were mutated. This is pretty problematic as well, as a lot of consumers of CDC data want the full row, not just the field that was updated. Are you aware of this issue?

**Comment by andrewstevenson** [comment]
closing as won't be implemented
