### ISSUE TITLE
Cassandra Connector Composite Primary Key

### ISSUE THREAD

**Issue by BeScrumpy** [Landoop/stream-reactor#281]
Expected behavior is that when given a composite key or part of one, it should be able to use the incremental mode.

With the token mode, what was observed is that it will continuously process and commit the same rows over and over again, and not drain properly.

Connect Distributed Configs
`bootstrap.servers=
group.id=connect-cluster
key.converter=org.apache.kafka.connect.storage.StringConverter
value.converter=org.apache.kafka.connect.storage.StringConverter
key.converter.schemas.enable=false
value.converter.schemas.enable=false
internal.key.converter=org.apache.kafka.connect.json.JsonConverter
internal.value.converter=org.apache.kafka.connect.json.JsonConverter
internal.key.converter.schemas.enable=false
internal.value.converter.schemas.enable=false
config.storage.topic=connect-configs
status.storage.topic=connect-status
offset.flush.interval.ms=10000
rest.advertised.host.name=
rest.advertised.port=
rest.host.name=
rest.port=`

Job
` "connect.cassandra.import.mode": "incremental",
    "connect.cassandra.kcql":"INSERT INTO cassandraDemo SELECT * FROM ucid_by_nelson PK euid_nel INCREMENTALMODE=TOKEN",`

**Comment by Antwnis** [comment]
Just a note - that for cassandra to work out UUID based on tokens, (maybe) all composite keys of a PK will need to be defined i.e. `PK f1,f2` 

This is something to be explored while coding up the solution

**Comment by CodeSmell** [comment]
@BeScrumpy 
Is the Cassandra cluster using the Byte Ordered Partitioner?
That is required for INCREMENTAL MODE of TOKEN to work correctly.

**Comment by Antwnis** [comment]
That's interesting. So i guess if Byte Ordered Partitioner is in use - and a composite key exists , using the first one is important .. the docs should be updated to contain your above @CodeSmell  note

**Comment by CodeSmell** [comment]
Looking at the original PR, I think the original idea was to only support one column as the UUID/key
https://github.com/datamountaineer/stream-reactor/pull/198

I mentioned the Byte Ordered Partitioner b/c it is generally not recommended due to creating hotspots in the cluster. However, if Byte Ordered Partitioner is not used, the KC connector will miss all of the new rows whose token(PK column) falls "behind" the token recorded as the offset. This is b/c Cassandra's other partitioners don't order the tokens.

**Comment by andrewstevenson** [comment]
Closing. Please reopen if required.
