### ISSUE TITLE
Many dependencies using influxdb connector

### ISSUE THREAD

**Issue by ehudl** [Landoop/stream-reactor#336]
<dependency>
    <groupId>com.datamountaineer</groupId>
    <artifactId>kafka-connect-influxdb</artifactId>
    <version>0.3.0</version>
</dependency>

I added  the above maven dependency to my kafka-connect project and I discovered many dependencies as a result of it. 
Am I missing something ?

**Comment by stheppi** [comment]
Hi @ehudl ,
  First, thanks for trying out our connector. Now moving to your request, I am not sure what is the actual issue here.  
  The idea with the library is that is a self contained Kafka Connect sink.   You are not supposed to add   the lib as a dependency to your project. 
  Furthermore,  do you expect to use one library that needs Kafka, influxdb and expect 0 dependencies? 
  I will have to close this, since is not an issue.
